<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Omnipay\\TwoCheckout\\' => array($vendorDir . '/omnipay/2checkout/src'),
    'Omnipay\\Stripe\\' => array($vendorDir . '/omnipay/stripe/src'),
    'Omnipay\\PayPal\\' => array($vendorDir . '/omnipay/paypal/src'),
    'Omnipay\\MobilPay\\' => array($vendorDir . '/business-mastery/omnipay-mobilpay/src/BusinessMastery/Mobilpay'),
    'Http\\Promise\\' => array($vendorDir . '/php-http/promise/src'),
    'Http\\Client\\' => array($vendorDir . '/php-http/httplug/src'),
    'Http\\Adapter\\Guzzle6\\' => array($vendorDir . '/php-http/guzzle6-adapter/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
